# Generated by Django 3.2.12 on 2022-02-19 19:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uniqueCode',
            field=models.UUIDField(blank=True, default='5c88a54862644acf8cb741679d08d04b', unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(default=100000),
        ),
    ]
