# Generated by Django 3.2.12 on 2022-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220409_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uniqueCode',
            field=models.UUIDField(blank=True, default='6b60c33c5e4146cdab7623ca2458baa2', unique=True),
        ),
    ]
