# Generated by Django 3.2.12 on 2022-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_uniquecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uniqueCode',
            field=models.UUIDField(blank=True, default='aa10285b573844ac890fe18031d118c6', unique=True),
        ),
    ]
