# Generated by Django 3.2.12 on 2022-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingperstock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
