# Generated by Django 3.2.12 on 2022-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='holdingperstock',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
