# Generated by Django 3.2.12 on 2022-04-09 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_auto_20220214_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_symbol', models.CharField(max_length=100)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('sell_date', models.DateTimeField(null=True)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField(null=True)),
                ('profit_loss', models.FloatField(null=True)),
                ('buy_share', models.IntegerField()),
                ('sell_share', models.IntegerField(null=True)),
                ('equity_brokerage', models.FloatField()),
                ('stt', models.FloatField()),
                ('stamp_duty', models.FloatField()),
                ('exchange_transaction', models.FloatField()),
                ('sebi_turnover', models.FloatField()),
                ('gst', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
